# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('sname', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('usba_id', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration_min', models.IntegerField(default=30)),
                ('cost_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('usba_id', models.CharField(blank=True, max_length=32)),
                ('njbc_id', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration_min', models.IntegerField(default=30)),
                ('fee_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=32)),
                ('session_name', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField()),
                ('duration_min', models.IntegerField(default=30)),
                ('court', models.CharField(max_length=8)),
                ('session_note', models.CharField(max_length=128)),
                ('instructors', models.ManyToManyField(through='club.InstructorParticipation', to='club.Instructor')),
                ('players', models.ManyToManyField(through='club.PlayerParticipation', to='club.Person')),
            ],
        ),
        migrations.AddField(
            model_name='playerparticipation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Session'),
        ),
        migrations.AddField(
            model_name='instructorparticipation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Session'),
        ),
    ]
