# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropin_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nonmember_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sibling_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='junior_training_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_min', models.IntegerField(default=3)),
                ('member_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nonmember_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sibling_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='playpass_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_count', models.IntegerField(default=3)),
                ('pass_expiry_month_limit', models.IntegerField(default=3)),
                ('adult_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('junior_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='private_coaching_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.IntegerField(default=3)),
                ('duration_min', models.IntegerField(default=3)),
                ('member_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nonmember_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coach', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('sibling_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='summer_camp_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nonmember_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sibling_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='timebase_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(max_length=32)),
                ('individual_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('spouse_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('junior_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='instructor',
            name='emergency_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='instructor',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='njbc_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='njbc_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='playerparticipation',
            name='use_sibling_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
