# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20160829_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='session',
            name='persons_count',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=48),
        ),
    ]
