# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20160926_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sibling_parent',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='playerparticipation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
