# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20160928_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sibling_parent',
            new_name='sibling_eldest',
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='njbc_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='njbc_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
