# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20161001_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='njbc_id',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sname',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
