# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20161002_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
